import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "About - My first app",
    description: "Generated by create next app",
  };

const Page = () => {
  return (
    <div>about
        <Link href="/" className="text-blue-500 block">
        Home</Link>
    </div>
  )
}

export default Page